const assert = require('node:assert/strict');
const { TikToolProvider } = require('../dist-electron/providers/TikToolProvider');
const lines = [], events = [];
const provider = new TikToolProvider('private-key', line => lines.push(line));
provider.onEvent(event => events.push(event));
const displayType = 'ttlive_superFan_commentNotif_superFanJoined';
const send = (event, data) => provider.handle({ event, data: { user: { uniqueId: 'xsilverx25' }, ...data } });
send('barrage', { msgId: 'entrance-1', displayType });
assert.equal(events.length, 1, 'Raw Super Fan entrance must be delivered');
assert.equal(events[0].type, 'SuperFanJoin');
assert.equal(events[0].user, 'xsilverx25');
send('superFanJoin', { msgId: 'entrance-1', displayType });
assert.equal(events.length, 1, 'Raw and derived copies of the same event trigger only once');
assert.equal(provider.diagnostics().recentEntrances.at(-1).outcome, 'Ignored: duplicate event ID');
send('barrage', { msgId: 'entrance-2', displayType });
send('barrage', { displayType });
send('barrage', { displayType });
assert.equal(events.length, 4, 'Distinct entrances and no-ID re-entries all pass');
send('barrage', { displayType: 'ttlive_superFan_commentNotif_someoneBecameSuperFan' });
send('barrage', { displayType: 'other', content: 'PRIVATE CONTENT superFanJoined' });
assert.equal(events.length, 4, 'Unrelated announcements and message text cannot masquerade as entrances');
send('member', { msgId: 'member-1', user: { nickname: 'Silver Display Name' }, uniqueId: 'xsilverx25' });
assert.equal(events.at(-1).user, 'xsilverx25', 'Available handle takes precedence over display name');
const last = provider.diagnostics().recentEntrances.at(-1);
assert.equal(last.username, 'xsilverx25');
assert.equal(last.outcome, 'Delivered: Join');
send('barrage', { displayType: 'private-key', content: 'PRIVATE CONTENT' });
assert.ok(!JSON.stringify(provider.diagnostics()).includes('private-key'));
assert.ok(!lines.join('\n').includes('PRIVATE CONTENT'));
for (let n = 0; n < 55; n++) send('member', { msgId: 'bounded-' + n });
assert.equal(provider.diagnostics().recentEntrances.length, 50);
console.log('Passed: raw entrance classification, repeated entrances, duplicate raw/derived events, unrelated announcements, username matching, bounded/redacted diagnostics.');
