const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
const exportsObject = {};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/giftActions.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2021 } }).outputText, { exports: exportsObject });
const { matchesGiftAction: matches } = exportsObject;
const rule = { enabled: true, giftName: 'Rose', minimumCount: 5 };
const event = { type: 'Gift', giftName: ' ROSE ', count: 5, comboComplete: true };
assert.equal(matches(rule, event), true);
assert.equal(matches(rule, { ...event, count: 4 }), false);
assert.equal(matches(rule, { ...event, count: 10 }), true);
assert.equal(matches(rule, { ...event, comboComplete: false }), false);
assert.equal(matches(rule, { ...event, giftName: 'Rose Bouquet' }), false);
assert.equal(matches(rule, { ...event, type: 'Chat' }), false);
assert.equal(matches({ ...rule, enabled: false }, event), false);
assert.equal(matches({ ...rule, giftName: ' ' }, { ...event, giftName: ' ' }), false);
assert.equal(matches({ ...rule, minimumCount: 1 }, { type: 'Gift', giftName: 'Rose' }), true);
assert.equal(matches(JSON.parse(JSON.stringify(rule)), event), true);
console.log('Gift action rules passed: exact matching, quantities, combo completion, disabled rules, and persistence.');
const { giftWebhookUrl, luckyWheelUrl } = exportsObject;
assert.equal(giftWebhookUrl(luckyWheelUrl, { user: 'Gold Fan & friends#1' }), 'http://localhost:5730/wheel?id=0&userName=Gold%20Fan%20%26%20friends%231');
assert.equal(giftWebhookUrl(luckyWheelUrl, { user: '{gift}', giftName: 'Rose' }), 'http://localhost:5730/wheel?id=0&userName=%7Bgift%7D');
console.log('Lucky Wheel sender substitution and URL encoding passed.');
