const assert = require("node:assert/strict");
const { LikesTracker } = require("../dist-electron/likesTracker");
const { TikToolProvider } = require("../dist-electron/providers/TikToolProvider");
const tracker = new LikesTracker();
const provider = new TikToolProvider("test");
provider.onRoom(room => tracker.startStream("streamer", room));
provider.onEvent(event => { if (event.type === "Like") tracker.add(event); });
const send = (data) => provider.handle({ event: "like", data });
provider.handle({ event: "roomInfo", roomId: "first-room" });
send({ msgId: "a", user: { uniqueId: "Alice", profilePictureUrl: "https://example.com/alice.png" }, likeCount: 10, totalLikeCount: 500 });
send({ msgId: "a", user: { uniqueId: "Alice", profilePictureUrl: "https://example.com/alice.png" }, likeCount: 10, totalLikeCount: 500 });
assert.equal(tracker.snapshot().trackedLikes, 10, "Duplicate deliveries must not increase counts");
send({ msgId: "b", user: { uniqueId: "@ALICE" }, likeCount: 5, totalLikeCount: 515 });
send({ msgId: "c", user: { uniqueId: "Bob" }, likeCount: 15, totalLikeCount: 510 });
let state = tracker.snapshot();
assert.equal(state.viewers, 2);
assert.equal(state.leaders.find(row => row.user === "ALICE").profilePictureUrl, "https://example.com/alice.png", "Provider pictures survive later likes without an image");
assert.equal(state.totalLikes, 515, "Out-of-order totals do not reduce the LIVE total");
assert.deepEqual(state.leaders.map(row => row.rank), [1, 1], "Ties share a rank");
send({ user: { uniqueId: "Bob" }, likeCount: 2 });
send({ user: { uniqueId: "Bob" }, likeCount: 2 });
assert.equal(tracker.snapshot().leaders[0].likes, 19, "Separate bursts without IDs are not dropped");
send({ msgId: "bad", user: { uniqueId: "Invalid" }, likeCount: -10 });
send({ msgId: "missing-user", likeCount: 20, totalLikeCount: 600 });
assert.equal(tracker.snapshot().viewers, 2, "Unknown users do not become a fictitious viewer");
assert.equal(tracker.snapshot().totalLikes, 600);
const before = tracker.snapshot().trackedLikes;
provider.handle({ event: "roomInfo", data: { roomId: "first-room" } });
assert.equal(tracker.snapshot().trackedLikes, before, "Same-room reconnect preserves ranking");
provider.handle({ event: "roomInfo", roomId: "second-room" });
assert.equal(tracker.snapshot().trackedLikes, 0, "A new stream clears rankings");
assert.equal(tracker.snapshot().totalLikes, null);
send({ msgId: "next", user: { uniqueId: "Alice" }, likeCount: 4, totalLikeCount: 4 });
tracker.reset();
tracker.add({ id: "next", type: "Like", user: "Alice", likeCount: 4 });
assert.equal(tracker.snapshot().trackedLikes, 0, "A replay cannot repopulate a manual reset");
for (let i = 0; i < 15; i++) tracker.add({ id: "many" + i, type: "Like", user: "viewer" + i, likeCount: i + 1 });
assert.equal(tracker.snapshot().leaders.length, 10);
assert.equal(tracker.snapshot().viewers, 15);
tracker.startStream("other-streamer", "");
assert.equal(tracker.snapshot().trackedLikes, 0, "Changing host clears the previous ranking");
console.log("Passed: like parsing, totals, ties, deduplication, bursts, missing identities, top 10, reconnects, and resets.");

const pictures = new LikesTracker();
pictures.add({ id: "pic1", type: "Like", user: "viewer", likeCount: 1, profilePictureUrl: "https://example.com/first.png" });
pictures.add({ id: "pic2", type: "Like", user: "viewer", likeCount: 1, profilePictureUrl: "javascript:alert(1)" });
assert.equal(pictures.snapshot().leaders[0].profilePictureUrl, "https://example.com/first.png");
pictures.add({ id: "pic3", type: "Like", user: "viewer", likeCount: 1, profilePictureUrl: "https://example.com/new.png" });
assert.equal(pictures.snapshot().leaders[0].profilePictureUrl, "https://example.com/new.png");
console.log("Passed: profile-picture parsing, retention, updates, and invalid-URL fallback.");
