import {useState} from 'react';
export type SearchMoment={start:number;end:number;peakAt:number;levelDb:number;reason:string;categories?:string[];sources?:string[]};
export type MontageCut={start:number;end:number;category:string};
export default function MomentWorkflow({recording,api,busy,action,found,current,cuts,setCuts,style,setMessage,setAnalyzing,setProgress}:{recording:{id:string;width:number;height:number;hasAudio:boolean};api:any;busy:boolean;action:(f:()=>Promise<void>)=>void;found:(m:SearchMoment[])=>void;current:{start:number;end:number};cuts:MontageCut[];setCuts:(cuts:MontageCut[])=>void;style:{cameraFocus:boolean;audioPolish:boolean;font:string;wordHighlight:boolean};setMessage:(s:string)=>void;setAnalyzing:(b:boolean)=>void;setProgress:(n:number)=>void}){
 const [audio,setAudio]=useState(true),[spoken,setSpoken]=useState(true),[visual,setVisual]=useState(false);
 const [phrases,setPhrases]=useState({'kill':'Got one','multi-kill':'Team wipe','win':'Victory','general':'Clip that'});
 const [before,setBefore]=useState(8),[after,setAfter]=useState(6);
 const vertical=Math.abs(recording.width/recording.height-9/16)<0.02;
 const [region,setRegion]=useState({x:0,y:vertical?33:0,width:100,height:vertical?50:100});
 const [category,setCategory]=useState('general'),[kind,setKind]=useState('all'),[target,setTarget]=useState(30),[versions,setVersions]=useState(3),[captions,setCaptions]=useState(false);
 const selected=cuts.filter(c=>kind==='all'||(kind==='kills'?['kill','multi-kill'].includes(c.category):c.category===kind));
 return <section className="card form">
  <h2>Find moments in several ways</h2>
  <div className="row"><label><input type="checkbox" checked={audio} disabled={busy||!recording.hasAudio} onChange={e=>setAudio(e.target.checked)}/> General audio highlights</label><label><input type="checkbox" checked={spoken} disabled={busy||!recording.hasAudio} onChange={e=>setSpoken(e.target.checked)}/> Spoken cues</label><label><input type="checkbox" checked={visual} disabled={busy} onChange={e=>setVisual(e.target.checked)}/> Visual text cues (experimental)</label></div>
  {spoken && Object.entries(phrases).map(([key,value])=><label key={key}>{key==='multi-kill'?'Multi-kill':key==='general'?'General highlight':key==='win'?'Win':'Kill'} phrases (comma separated)<input value={value} disabled={busy} onChange={e=>setPhrases(p=>({...p,[key]:e.target.value}))}/></label>)}
  <div className="row"><label>Seconds before cue<input type="number" min={0} max={45} value={before} disabled={busy} onChange={e=>setBefore(Number(e.target.value))}/></label><label>Seconds after cue<input type="number" min={1} max={30} value={after} disabled={busy} onChange={e=>setAfter(Number(e.target.value))}/></label></div>
  {visual && <><small>Searches for “Eliminated” and “Victory Royale” using Windows OCR, sampling every 2 seconds. Crop to gameplay to reduce matches from chat or overlays. Brief messages and stylized text can be missed; matches need review.</small><div className="row">{Object.entries(region).map(([key,value])=><label key={key}>Region {key} (%)<input type="number" min={0} max={100} disabled={busy} value={value} onChange={e=>setRegion(r=>({...r,[key]:Number(e.target.value)}))}/></label>)}</div></>}
  <button disabled={busy||!(audio||spoken||visual)} onClick={()=>action(async()=>{setAnalyzing(true);setProgress(0);const cues=Object.entries(phrases).flatMap(([category,value])=>value.split(',').map(phrase=>({category,phrase:phrase.trim()})).filter(c=>c.phrase));const result=await api.search({id:recording.id,options:{audio:audio&&recording.hasAudio,spoken:spoken&&recording.hasAudio,visual,cues,before,after,region:Object.fromEntries(Object.entries(region).map(([k,v])=>[k,v/100]))}});found(result.highlights);setMessage(result.message);})}>Search selected methods</button>
  <small>Spoken search uses your local caption setup and may take time on a full stream. Search results replace the previous list; saved montage cuts remain.</small>
  <h2>Montage</h2>
  <div className="row"><label>Current cut category<select value={category} disabled={busy} onChange={e=>setCategory(e.target.value)}><option value="general">General highlight</option><option value="kill">Kill</option><option value="multi-kill">Multi-kill</option><option value="win">Win</option></select></label><button disabled={busy||current.end<=current.start||cuts.length>=64} onClick={()=>{if(!cuts.some(c=>c.start===current.start&&c.end===current.end))setCuts([...cuts,{...current,category}]);}}>Add selected cut to montage</button></div>
  <small>Review a suggestion, adjust its cut, then add it here. Only these saved cuts are exported.</small>
  {cuts.map((c,i)=><div className="row" key={i}><span>Cut {i+1}: {c.start.toFixed(2)}–{c.end.toFixed(2)}s · {c.category}</span><button disabled={busy} onClick={()=>setCuts(cuts.filter((_,n)=>n!==i))}>Remove cut {i+1}</button></div>)}
  <div className="row"><label>Include<select value={kind} disabled={busy} onChange={e=>setKind(e.target.value)}><option value="all">Mixed highlights</option><option value="kills">Kills and multi-kills</option><option value="win">Wins</option><option value="general">General highlights</option></select></label><label>Maximum length<select value={target} disabled={busy} onChange={e=>setTarget(Number(e.target.value))}>{[15,30,60].map(n=><option key={n} value={n}>{n} seconds</option>)}</select></label><label>Versions<select value={versions} disabled={busy} onChange={e=>setVersions(Number(e.target.value))}>{[1,2,3].map(n=><option key={n} value={n}>Up to {n}</option>)}</select></label></div>
  <label><input type="checkbox" checked={captions} disabled={busy||!recording.hasAudio} onChange={e=>setCaptions(e.target.checked)}/> Generate captions for montage cuts</label>
  <small>Versions use recording order, reverse order, and alternating cuts. Duplicate versions are skipped. Shorter source selections produce shorter montages. Uses your camera, font, word-highlight, and audio settings below.</small>
  <button disabled={busy||!selected.length} onClick={()=>action(async()=>{setAnalyzing(true);setProgress(0);const files=await api.montage({id:recording.id,clips:selected,target,versions,captions,...style});if(files)setMessage(`Montage versions saved: ${files.join(' · ')}`);})}>Export montage versions ({selected.length} cuts)</button>
 </section>;
}
